### ISSUE TITLE
Implement comments for stories and events

### ISSUE THREAD

**Issue by sam9116** [BsquaredatUofA/Web#5]
~~1.creating the tables in databse~~
~~2.implement the buttons on the stories page~~ and events page
3. handling the incoming comments and save them into database
4. search and display comments saved for each event/story

**Comment by sam9116** [comment]
@Tan9ster I will also need u help setting up the visual container for each comment, expect something like the tiles for stories on the index page

**Comment by Tan9ster** [comment]
which file is the comments going to be in?

**Comment by sam9116** [comment]
The comments will be placed in events.php and single_stories.php
